#!/bin/bash -e

function multidisplay_config() {
    if [ -z $1 ]; then
        echo "Usage : xdisplay ${1}"
        return
    fi
    echo "xrandr --output ${1} --off"
    xrandr --output $1 --off
}

multidisplay_config $1

