#!/bin/sh

function get_airport_status() {
    if [ -z $(iwconfig wlp5s0 | grep -o unassociated) ]; then
        ssid=`iwconfig wlp5s0 | grep -oP '(?<=").+(?="\s)'`
        rssi=`iwconfig wlp5s0 | grep -oP '(?<=level=)\d+(?=/100\s)'`
        signals=(▂ ▃ ▄ ▆ █ ▁)
        signal=""
        rssi_=$((rssi / 20 + 1))
        if [ $((rssi % 20)) -eq 0 ] && [ ${rssi_} -gt 1 ]; then
            rssi_=$((rssi_ - 1))
        fi
        for ((i=0; i < 5; i++)); do
            if [ $i -lt ${rssi_} ]; then
                signal=${signal}${signals[$i]}
            elif [ $i -ge ${rssi_} ]; then
                signal=${signal}${signals[5]}
            fi
        done
        airport=" #[fg=colour10,underscore]${ssid}#[default] | ${signal} "
    else
        airport="#[fg=red,bold] ✘ #[default]"
    fi
    echo "#[bold]|#[default]${airport}#[bold]|#[default]"
}

function main() {
    local airport=$(get_airport_status)
    echo "${airport}"
}

main $@
