# Last Change : Sun 02 Dec 2018 16:14:59.
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_vert_resize=1
    let g:winresizer_horiz_resize=1
'''

[[plugins]]
repo = 'vim-scripts/autodate.vim'
hook_add = '''
    let g:autodate_lines=20
    let g:autodate_keyword_pre='Last Change : '
    let g:autodate_format="%a %d %b %Y %H:%M:%S"
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
hook_add = '''
    nnoremap <silent><Leader>r :QuickRun<CR>
    nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
    autocmd FileType quickrun nnoremap <silent><buffer>q :quit<CR>
'''
hook_add = '''
    let g:quickrun_config={
    \    "_" : {
    \        "outputter/buffer/split" : ":botright 8sp",
    \        "outputter/buffer/into" : 1,
    \        "outputter/error/error" : "quickfix",
    \        "outputter/quickfix/errorformat" : "%f :%l,%m in on line %l",
    \        "outputter/error/success" : "buffer",
    \        "outputter/buffer/close_on_empty" : 1,
    \        "outputter" : "error",
    \    }
    \}
'''

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
    " ctrl + /で選択行のコメントアウト
    nmap <C-_> <Plug>(caw:hatpos:toggle)
    vmap <C-_> <Plug>(caw:hatpos:toggle)
    " imap <C-_> <esc><Plug>(caw:hatpos:toggle)<S-$>a
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

