[[plugins]]
repo = 'popkirby/lightline-iceberg'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
           \  'colorscheme':'deus',
           \  'mode_map': { 'c': 'NORMAL' },
           \  'active': {
           \    'left': [ [ 'mode', 'paste' ], [ 'filetype', 'fileencoding' ] ],
           \    'right': [ [ 'lineinfo' ], [ 'fugitive', 'fileformat' ] ] },
           \  'component_function': {
           \    'modified': 'LightlineModified',
           \    'readonly': 'LightlineReadonly',
           \    'fugitive': 'LightlineFugitive',
           \    'filename': 'LightlineFilename',
           \    'fileformat': 'LightlineFileformat',
           \    'filetype': 'LightlineFiletype',
           \    'fileencoding': 'LightlineFileencoding',
           \    'mode': 'LightlineMode' },
           " \  'separator': {'left':'', 'right':''},
           " \  'subseparator':{'left':'', 'right':''},
           \  }
    let g:lightline.tabline={
           \  'filename': 'tabs',
           \  'right':[[]] }
    let g:lightline.component={
           \  'lineinfo':'%-2v',
           \  'filetype':'%{&ft!=#""?ft:"-"}',
           \  'paste':'%{&paste?"P":""}' }
    let g:lightline.tab={
           \  'active': ['tabnum', 'filename', 'modified'],
           \  'inactive': ['tabnum', 'filename', 'modified'] }

    let s:palette = g:lightline#colorscheme#deus#palette
    let s:blue = 14
    let s:dark_blue = 39
    let s:green = 114
    let s:purple = 170
    let s:red = 204
    let s:black = 235
    let s:white = 145
    let s:gray = 236

    let s:g_normal  = [ '#292c33', '#8eb2f7' ]
    let s:g_insert  = [ '#292c33', '#98c379' ]
    let s:g_visual  = [ '#292c33', '#c678dd' ]
    let s:g_replace = [ '#292c33', '#e06c75' ]

    " palette Normal
    let s:palette.normal.left   = [ [ '#292c33', '#8eb2f7', s:black, s:dark_blue,  'bold' ], [ '#8eb2f7', '#292c33',  s:dark_blue,  s:black ] ]
    " let s:palette.normal.right  = [ [ '#292c33', '#8eb2f7', s:black, s:dark_blue,  'bold' ], [ '#abb2bf', '#292c33', s:white, s:black ], [ '#8eb2f7', '#292c33', s:dark_blue, s:black ] ]
    let s:palette.normal.right  = [ [ '#292c33', '#8eb2f7', s:black, s:dark_blue,  'bold' ], [ '#8eb2f7', '#292c33', s:dark_blue, s:black ] ]
    let s:palette.normal.middle = [ s:palette.normal.left[1] ]

    " palette Insert
    let s:palette.insert.left   = [ [ '#292c33', '#98c379', s:black, s:green, 'bold' ], [ '#98c379', '#292c33', s:green, s:black ] ]
    " let s:palette.insert.right  = [ [ '#292c33', '#98c379', s:black, s:green, 'bold' ], [ '#abb2bf', '#292c33', s:white, s:gray  ], [ '#98c379', '#292c33', s:green, s:black ] ]
    let s:palette.insert.right  = [ [ '#292c33', '#98c379', s:black, s:green, 'bold' ], [ '#98c379', '#292c33', s:green, s:black ] ]
    let s:palette.insert.middle = [ s:palette.insert.left[1] ]

    " palette Visual
    let s:palette.visual.left   = [ [ '#292c33', '#c678dd', s:black, s:purple, 'bold' ], [ '#c678dd', '#292c33', s:purple, s:black ] ]
    " let s:palette.visual.right  = [ [ '#292c33', '#c678dd', s:black, s:purple, 'bold' ], s:palette.normal.right[1], [ '#c678dd', '#292c33', s:purple, s:black ] ]
    let s:palette.visual.right  = [ [ '#292c33', '#c678dd', s:black, s:purple, 'bold' ], [ '#c678dd', '#292c33', s:purple, s:black ] ]
    let s:palette.visual.middle = [ s:palette.visual.left[1] ]

    " palette Replace
    let s:palette.replace.left   = [ [ '#292c33', '#e06c75', s:black, s:red, 'bold' ], [ '#e06c75', '#292c33', s:red, s:black ] ]
    " let s:palette.replace.right  = [ [ '#292c33', '#e06c75', s:black, s:red, 'bold' ], s:palette.normal.right[1], [ '#e06c75', '#292c33', s:red, s:black ] ]
    let s:palette.replace.right  = [ [ '#292c33', '#e06c75', s:black, s:red, 'bold' ], [ '#e06c75', '#292c33', s:red, s:black ] ]
    let s:palette.replace.middle = [ s:palette.replace.left[1] ]

    let s:palette.tabline.left   = [ s:palette.normal.left[1] ]
    let s:palette.tabline.tabsel = [ s:palette.normal.left[0] ]
    let s:palette.tabline.middle = [ [ '#161821', '#161821', s:black, s:dark_blue ] ]
    let s:palette.tabline.right  = [ [ '#8eb2f7', '#161821', s:dark_blue, s:black ] ]

    function! LightlineModified()
        return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
    endfunction

    function! LightlineReadonly()
        return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
    endfunction

    function! LightlineFilename()
        return ('' != LightlineReadonly() ? LightlineReadonly() . ' ' : '') .
             \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
             \  &ft == 'unite' ? unite#get_status_string() :
             \  &ft == 'vimshell' ? vimshell#get_status_string() :
             \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
             \ ('' != LightlineModified() ? ' ' . LightlineModified() : '')
    endfunction

    " function! LightlineFugitive()
    "     if exists('*fugitive#head')
    "         let branch = fugitive#head()
    "         " return branch != '' ? "\ue0a0 ".branch : ''
    "         return branch != '' ? " ".branch:''
    "     endif
    " endfunction

    function! LightlineFugitive()
        if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
            return " ".fugitive#head()
        else
            return ''
        endif
    endfunction

    function! LightlineFileformat()
        return winwidth(0) > 70 ? &fileformat : ''
    endfunction

    function! LightlineFiletype()
        return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
    endfunction

    function! LightlineFileencoding()
        return winwidth(0) > 70 ? (&fenc !=# '' ? &fenc : &enc) : ''
    endfunction

    function! LightlineMode()
        return winwidth(0) > 60 ? lightline#mode() : ''
    endfunction
'''
