[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_vert_resize=1
    let g:winresizer_horiz_resize=1
'''

[[plugins]]
repo = 'vim-scripts/autodate.vim'
hook_add = '''
    let g:autodate_lines=20
    let g:autodate_keyword_pre='Last Change : '
    let g:autodate_format="%a %d %b %Y %H:%M:%S"
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_source = '''
    nmap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"

    :command Run QuickRun
    let g:quickrun_config={
        "_" : {
            "outputter/buffer/split" : ":botright 8sp",
            "outputter/buffer/close_on_empty" : 1,
            "outputter/error/error" : "quickfix",
            "outputter/error/success" : "buffer",
            "outputter/buffer/into" : 1,
            "outputter" : "error",
        }
    }
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
    " ctrl + /で選択行のコメントアウト
    nmap <C-_> <Plug>(caw:hatpos:toggle)
    vmap <C-_> <Plug>(caw:hatpos:toggle)
    " imap <C-_> <esc><Plug>(caw:hatpos:toggle)<S-$>a
'''
